### ISSUE TITLE
Broken links to datasets

### ISSUE THREAD

**Issue by willkraemer** [asmitapoddar/nowplaying-RS-Music-Reco-FM#3]
Both these links are broken when trying to download the datasets: 

- http://dbis-nowplaying.uibk.ac.at/wp-content/uploads/nowplayingrs.zip
- http://dbis-nowplaying.uibk.ac.at/wp-content/uploads/nowplayingrs_train_test.zip

**Comment by asmitapoddar** [comment]
I have put the updated link:
[https://zenodo.org/record/3242238#.XP311EMRXCI](https://zenodo.org/record/3242238#.XP311EMRXCI)

**Comment by asmitapoddar** [comment]
You can find the updated dataset here: [https://zenodo.org/record/3248543](https://zenodo.org/record/3248543).
